name: Publish to Hex.pm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Hex.pm Configuration
      run: |
        mkdir -p ~/.config/rebar3
        echo "{plugins, [rebar3_hex]}." > ~/.config/rebar3/rebar.config
        echo '${{ secrets.HEX_CONFIG }}' > ~/.config/rebar3/hex.config
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: '25.3'
        elixir-version: '1.15.4'
        rebar3-version: '3.22.1'

    - name: Publish to Hex.pm
      run: |
        mix local.rebar --force
        mix local.hex --force
        rebar3 update
        echo "" | rebar3 hex publish --yes
